### ISSUE TITLE
Grammar test script looking for wrong extension

### ISSUE THREAD

**Issue by rtoal** [dmoini/casper#1]
You have `.pls` but you mean `.ded` I think?

**Comment by dmoini** [comment]
Which file are you referring to? @rtoal

**Comment by rtoal** [comment]
Grep for `pls`

TL;DR 
https://github.com/dmoini/casper/blob/master/test/grammar/grammar.test.js
https://github.com/dmoini/casper/blob/master/test/grammar/grammar-test.js

Oh and by the way you don't want _both_ of those files, so keep one and remove the other (and fix the file extension too :) )

**Comment by doorDoes** [comment]
I've gone ahead and removed `grammar-test.js` and adjusted the proper test file to reflect casper's file extension. Closing issue
